import type { Question } from "./types";

const Q = (
  id: string,
  title: string,
  hint: string,
  aLabel: string,
  aTraits: Question["optionA"]["traits"],
  bLabel: string,
  bTraits: Question["optionB"]["traits"],
  category: Question["category"],
): Question => ({
  id,
  title,
  hint,
  optionA: { label: aLabel, traits: aTraits },
  optionB: { label: bLabel, traits: bTraits },
  category,
  active: true,
});

// Level 1 — "Discover Your Vibe". Premium, warm, conversational binary choices.
export const SEED_QUESTIONS: Question[] = [
  Q(
    "q-coffee",
    "Coffee or Tea?",
    "The drink that starts your day.",
    "Coffee",
    { Lifestyle: 2 },
    "Tea",
    { Lifestyle: 2 },
    "Food",
  ),
  Q(
    "q-weekend",
    "Ideal weekend?",
    "Where does the time go when nobody's watching?",
    "Spontaneous road trip",
    { Adventure: 3, Social: 1 },
    "Cozy day at home",
    { Lifestyle: 3, Family: 1 },
    "Lifestyle",
  ),
  Q(
    "q-vacation",
    "Dream vacation?",
    "Picture the view from the window.",
    "Mountains & hiking",
    { Adventure: 3, Lifestyle: 1 },
    "Beach & sunsets",
    { Lifestyle: 2, Social: 1 },
    "Travel",
  ),
  Q(
    "q-dinner",
    "Tonight's dinner?",
    "It's 7pm. You're hungry. What now?",
    "Try a new restaurant",
    { Adventure: 2, Social: 2 },
    "Cook together at home",
    { Family: 2, Lifestyle: 2 },
    "Food",
  ),
  Q(
    "q-friday",
    "Friday night plan?",
    "End of a long week. Pick the reset.",
    "House party with friends",
    { Social: 3 },
    "Quiet movie night",
    { Lifestyle: 2, Family: 1 },
    "Entertainment",
  ),
  Q(
    "q-money",
    "When it comes to money?",
    "Be honest about your default move.",
    "Save for the future",
    { Finance: 3, Planning: 2 },
    "Spend on experiences",
    { Adventure: 2, Lifestyle: 1 },
    "Finance",
  ),
  Q(
    "q-decisions",
    "Big decisions?",
    "How does the call usually get made?",
    "Plan every detail",
    { Planning: 3, Finance: 1 },
    "Trust your gut",
    { Adventure: 2, Social: 1 },
    "Personality",
  ),
  Q(
    "q-kids",
    "Future family?",
    "Five years from now — picture the house.",
    "Want kids someday",
    { Family: 3, Planning: 1 },
    "Happy without kids",
    { Lifestyle: 2, Adventure: 1 },
    "Family",
  ),
  Q(
    "q-conflict",
    "In a disagreement?",
    "Your real reflex, not your better one.",
    "Talk it out immediately",
    { Social: 2, Family: 2 },
    "Take space, return calm",
    { Planning: 2, Lifestyle: 1 },
    "Relationships",
  ),
  Q(
    "q-morning",
    "Mornings are for?",
    "What does your best morning look like?",
    "Sunrise workouts",
    { Adventure: 2, Lifestyle: 2 },
    "Slow coffee in bed",
    { Lifestyle: 3 },
    "Lifestyle",
  ),
  Q(
    "q-travel-style",
    "Travel style?",
    "Same destination — totally different trip.",
    "Backpack & hostels",
    { Adventure: 3, Finance: 1 },
    "Boutique hotels",
    { Lifestyle: 2, Finance: 1 },
    "Travel",
  ),
  Q(
    "q-music",
    "Music vibe?",
    "Where do you feel music in your body?",
    "Live concerts",
    { Social: 2, Adventure: 1 },
    "Curated playlists at home",
    { Lifestyle: 2 },
    "Entertainment",
  ),
  Q(
    "q-energy",
    "Energy source?",
    "After a long week, what fills you back up?",
    "Being around people",
    { Social: 3 },
    "Quiet solo time",
    { Lifestyle: 2, Planning: 1 },
    "Personality",
  ),
  Q(
    "q-holidays",
    "Holidays?",
    "Diwali, Christmas, long weekends — your pick.",
    "Big family gatherings",
    { Family: 3, Social: 2 },
    "Just us escape",
    { Adventure: 1, Lifestyle: 2 },
    "Family",
  ),
  Q(
    "q-love",
    "Show love by?",
    "Your most natural love language.",
    "Thoughtful gifts",
    { Planning: 2, Family: 1 },
    "Quality time",
    { Family: 2, Lifestyle: 2 },
    "Relationships",
  ),
  Q(
    "q-home",
    "Dream home?",
    "Open the door — what do you see?",
    "City loft",
    { Lifestyle: 2, Social: 2 },
    "Countryside retreat",
    { Family: 2, Adventure: 1 },
    "Lifestyle",
  ),
  Q(
    "q-cook",
    "Cooking style?",
    "Saturday afternoon in the kitchen.",
    "Follow the recipe",
    { Planning: 3 },
    "Improvise everything",
    { Adventure: 2 },
    "Food",
  ),
  Q(
    "q-tv",
    "Friday show?",
    "Couch, blanket, snack. Now what?",
    "Binge a new series",
    { Lifestyle: 2 },
    "Rewatch a favorite",
    { Family: 1, Lifestyle: 1 },
    "Entertainment",
  ),
  Q(
    "q-splurge",
    "Splurge on?",
    "Found a little extra money. Where does it go?",
    "Experiences",
    { Adventure: 2, Social: 1 },
    "Things that last",
    { Finance: 2, Lifestyle: 1 },
    "Finance",
  ),
  Q(
    "q-future",
    "Future planning?",
    "How does next year live in your head?",
    "Five-year plan",
    { Planning: 3, Finance: 2 },
    "See what unfolds",
    { Adventure: 2 },
    "Personality",
  ),
  Q(
    "q-pets",
    "Pets?",
    "Furry chaos welcome?",
    "Yes, the more the better",
    { Family: 2, Lifestyle: 1 },
    "Maybe one, maybe none",
    { Lifestyle: 1, Planning: 1 },
    "Family",
  ),
  Q(
    "q-values",
    "Most important?",
    "When push comes to shove, this matters more.",
    "Loyalty & roots",
    { Family: 3, Planning: 1 },
    "Growth & freedom",
    { Adventure: 3, Lifestyle: 1 },
    "Values",
  ),
  Q(
    "q-date",
    "Perfect date?",
    "Pick the version of you you most want shown.",
    "Picnic in the park",
    { Lifestyle: 2, Family: 1 },
    "Rooftop cocktails",
    { Social: 2, Lifestyle: 1 },
    "Relationships",
  ),
  Q(
    "q-friends",
    "Friends circle?",
    "How do you like your people?",
    "Big & buzzing",
    { Social: 3 },
    "Small & close",
    { Family: 2, Lifestyle: 1 },
    "Personality",
  ),
];
