/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResultRouteImport } from './routes/result'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as Level3RouteImport } from './routes/level-3'
import { Route as Level2RouteImport } from './routes/level-2'
import { Route as Level1CompleteRouteImport } from './routes/level-1-complete'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GameRouteImport } from './routes/game'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayCodeRouteImport } from './routes/play.$code'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'
import { Route as JoinCodeRouteImport } from './routes/join_.$code'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const Level3Route = Level3RouteImport.update({
  id: '/level-3',
  path: '/level-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Level2Route = Level2RouteImport.update({
  id: '/level-2',
  path: '/level-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Level1CompleteRoute = Level1CompleteRouteImport.update({
  id: '/level-1-complete',
  path: '/level-1-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayCodeRoute = PlayCodeRouteImport.update({
  id: '/play/$code',
  path: '/play/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join_/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/game': typeof GameRoute
  '/join': typeof JoinRoute
  '/level-1-complete': typeof Level1CompleteRoute
  '/level-2': typeof Level2Route
  '/level-3': typeof Level3Route
  '/onboarding': typeof OnboardingRoute
  '/result': typeof ResultRoute
  '/setup': typeof SetupRoute
  '/join/$code': typeof JoinCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/game': typeof GameRoute
  '/join': typeof JoinRoute
  '/level-1-complete': typeof Level1CompleteRoute
  '/level-2': typeof Level2Route
  '/level-3': typeof Level3Route
  '/onboarding': typeof OnboardingRoute
  '/result': typeof ResultRoute
  '/setup': typeof SetupRoute
  '/join/$code': typeof JoinCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/game': typeof GameRoute
  '/join': typeof JoinRoute
  '/level-1-complete': typeof Level1CompleteRoute
  '/level-2': typeof Level2Route
  '/level-3': typeof Level3Route
  '/onboarding': typeof OnboardingRoute
  '/result': typeof ResultRoute
  '/setup': typeof SetupRoute
  '/join_/$code': typeof JoinCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/play/$code': typeof PlayCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/game'
    | '/join'
    | '/level-1-complete'
    | '/level-2'
    | '/level-3'
    | '/onboarding'
    | '/result'
    | '/setup'
    | '/join/$code'
    | '/lobby/$code'
    | '/play/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/game'
    | '/join'
    | '/level-1-complete'
    | '/level-2'
    | '/level-3'
    | '/onboarding'
    | '/result'
    | '/setup'
    | '/join/$code'
    | '/lobby/$code'
    | '/play/$code'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/game'
    | '/join'
    | '/level-1-complete'
    | '/level-2'
    | '/level-3'
    | '/onboarding'
    | '/result'
    | '/setup'
    | '/join_/$code'
    | '/lobby/$code'
    | '/play/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  GameRoute: typeof GameRoute
  JoinRoute: typeof JoinRoute
  Level1CompleteRoute: typeof Level1CompleteRoute
  Level2Route: typeof Level2Route
  Level3Route: typeof Level3Route
  OnboardingRoute: typeof OnboardingRoute
  ResultRoute: typeof ResultRoute
  SetupRoute: typeof SetupRoute
  JoinCodeRoute: typeof JoinCodeRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
  PlayCodeRoute: typeof PlayCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-3': {
      id: '/level-3'
      path: '/level-3'
      fullPath: '/level-3'
      preLoaderRoute: typeof Level3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-2': {
      id: '/level-2'
      path: '/level-2'
      fullPath: '/level-2'
      preLoaderRoute: typeof Level2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-1-complete': {
      id: '/level-1-complete'
      path: '/level-1-complete'
      fullPath: '/level-1-complete'
      preLoaderRoute: typeof Level1CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$code': {
      id: '/play/$code'
      path: '/play/$code'
      fullPath: '/play/$code'
      preLoaderRoute: typeof PlayCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join_/$code': {
      id: '/join_/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  GameRoute: GameRoute,
  JoinRoute: JoinRoute,
  Level1CompleteRoute: Level1CompleteRoute,
  Level2Route: Level2Route,
  Level3Route: Level3Route,
  OnboardingRoute: OnboardingRoute,
  ResultRoute: ResultRoute,
  SetupRoute: SetupRoute,
  JoinCodeRoute: JoinCodeRoute,
  LobbyCodeRoute: LobbyCodeRoute,
  PlayCodeRoute: PlayCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
